version: '3.1'

services:
  db:
    build: .
    container_name: nestjs-db
    restart: always
    ports:
      - "5432:5433"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nestjs
      